# Generated by Django 6.0.5 on 2026-06-05 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('flag_icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка флага')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('period_days', models.IntegerField(default=7, verbose_name='Период (дни)')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.currency', verbose_name='Валюта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
                'ordering': ['-query_date'],
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс к RUB')),
                ('source', models.CharField(default='Frankfurter API', max_length=50, verbose_name='Источник')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='monitor.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'История курса',
                'verbose_name_plural': 'История курсов',
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
